[theme]
background = "#2E3440"
primary = "#ECEFF4"
secondary = "#D8DEE9"
title = "#88C0D0"
playing = "#88C0D0"
playing_selected = "#81A1C1"
playing_bg = "#4C566A"
highlight = "#8FBCBB"
highlight_bg = "#3B4252"
error = "#2E3440"
error_bg = "#BF616A"
statusbar = "#81A1C1"
statusbar_progress = "#5E81AC"
statusbar_bg = "#2E3440"
cmdline = "#88C0D0"
cmdline_bg = "#2E3440"
